# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);


POST http://localhost:8080/__admin/http/api
Content-Type: application/json

{
  "path": "/mock/demo/http/api",
  "actions": [
    {
      "type": "delay",
      "name": "delay",
      "duration": 700
    }
  ],
  "contentType": "application/json",
  "response": "{\"l1\":{\"l1_1\":[\"l1_1_1\",\"l1_1_2\"],\"l1_2\":{\"l1_2_1\":121}},\"l2\":{\"l2_1\":null,\"l2_2\":true,\"l2_3\":{}}}"
}

###
POST http://localhost:8080/__admin/http/api
Content-Type: application/json

{
  "path": "/mock/demo/http/api",
  "actions": [
    {
      "type": "proxy",
      "name": "proxy",
      "target": "https://www.baidu.com/abcd"
    }
  ],
  "contentType": "application/json; charset=utf-8",
  "response": "{\"l1\":{\"l1_1\":[\"l1_1_1\",\"l1_1_2\"],\"l1_2\":{\"l1_2_1\":121}},\"l2\":{\"l2_1\":null,\"l2_2\":true,\"l2_3\":{}}}"
}

###
POST http://localhost:8080/__admin/http/api
Content-Type: application/json

{
  "path": "/mock/demo/http/api",
  "method": "post",
  "actions": [
    {
      "type": "proxy",
      "name": "proxy",
      "target": "https://www.baidu.com/abcd"
    },
    {
      "type": "delay",
      "name": "delay",
      "duration": 700
    }
  ],
  "contentType": "application/json; charset=utf-8",
  "response": "{\"l1\":{\"l1_1\":[\"l1_1_1\",\"l1_1_2\"],\"l1_2\":{\"l1_2_1\":121}},\"l2\":{\"l2_1\":null,\"l2_2\":true,\"l2_3\":{}}}",
  "description": ""
}

###
POST http://localhost:8080/mock/demo/http/api
Content-Type: application/x-www-form-urlencoded

id=99&content=new-element

###
POST http://localhost:8080/__admin/http/api
Content-Type: application/json

{
  "path": "/mock/demo/http/api/script/python",
  "method": "post",
  "actions": [
    {
      "name": "script",
      "type": "script",
      "scriptType": "PYTHON",
      "scriptPath": "72d3fb26-d114-4629-80aa-63ed1392f55c_aaaaaa.py.py"
    }
  ],
  "contentType": "application/xml; charset=utf-8",
  "response": "<result><data>3333</data><type>python</type></result>",
  "description": ""
}

###
POST http://localhost:8080/mock/demo/http/api/script/python
Content-Type: application/xml

<req>
    <data>5555</data>
    <type>python</type>w
</req>

###
POST http://localhost:8080/mock/demo/http/api/script/python?mmm=333&nn=ggg&nn=999
Content-Type: application/json
Cookie: kkkk=dfdsfdsfds;ddsss=eee

{
  "aaa": 3333,
  "bbbb": "python"
}

###
POST http://localhost:8080/mock/demo/http/api/script/python
Content-Type: application/x-www-form-urlencoded

aaa=3333&bbb=5555&ccc=9999&aaa=2222;bbb=1111

###
POST http://localhost:8080/__admin/http/script
Content-Type: multipart/form-data; boundary=----WebkitFormBoundaryABCD

------WebkitFormBoundaryABCD
Content-Disposition: form-data; name="file"; filename="aaaaaa.py"
Content-Type: text/x-python-script

< /Users/apple/Downloads/ImportArbitraryDataFromFileToSecureCRTSessions.py
------WebkitFormBoundaryABCD--

###


###
POST http://localhost:8080/__admin/http/script
Content-Type: multipart/form-data; boundary=----WebkitFormBoundary1234

------WebkitFormBoundary1234
Content-Disposition: form-data; name="file", filename="bbbbb.groovy"
Content-Type: application/octet-stream

< /Users/apple/Downloads/Untitled-2.groovy
------WebkitFormBoundary1234--

###
POST http://localhost:8080/__admin/http/api
Content-Type: application/json

{
  "path": "/mock/demo/http/api/script/groovy",
  "method": "post",
  "actions": [
    {
      "name": "script",
      "type": "script",
      "scriptType": "GROOVY",
      "scriptPath": "82a5b300-44ff-4e81-adc2-b187bb6d4ce6_Untitled-2.groovy.groovy"
    }
  ],
  "contentType": "application/xml; charset=utf-8",
  "response": "<result><data>3333</data><type>python</type></result>",
  "description": ""
}

###
POST http://localhost:8080/mock/demo/http/api/script/groovy
Content-Type: application/x-www-form-urlencoded

aaa=3333&bbb=5555&ccc=9999&aaa=2222;bbb=1111

###
